#!/usr/bin/env Rscript

################################################################################
#                                                                              #
#                                scRNA-tools app                               #
#    command line application for interacting with the scRNA-tools database    #
#                                                                              #
################################################################################

#### DOCOPT ####

"
scRNA-tools command line application

Usage:
    scrnatools add
    scrnatools update [<name>]
    scrnatools search [<name>]
    scrnatools build
    scrnatools archive [<name>]
    scrnatools restore [<arc>]
    scrnatools stats [--plot]
    scrnatools -h | --help
    scrnatools --version

Options:
  name          Name of a tool in the database
  arc           Name of an archive in the database
  -p, --plot    Whether to show plots
  -h --help     Show this help message.
  --version     Show version.
" -> DOCOPT

#### PACKAGES ####

suppressPackageStartupMessages({
    library(docopt)
})

#### SOURCE ####

source("app/logo.R")
source("app/ui.R")
source("app/sctool-class.R")
source("app/regex.R")
source("app/load.R")
source("app/add.R")
source("app/update.R")
source("app/search.R")
source("app/build.R")
source("app/analysis.R")
source("app/pkgs-cache.R")
source("app/references.R")
source("app/archive.R")
source("app/save.R")
source("app/git.R")
source("app/stats.R")

#### MAIN CODE ####

opts <- docopt(DOCOPT, version = "0.2.1")

logo <- get_logo()
cat(logo, "\n")

check_status()

dir <- "database"
data_dir <- "docs/data"
plot_dir <- "docs/plots"

database <- load_database(dir)
pkgs_cache <- load_pkgs_cache(dir)

if (opts$add) {
    database <- add_tool(database, pkgs_cache)
}

if (opts$update) {
    database <- update_tool(database, pkgs_cache, opts$name)
}

if (opts$search) {
    search(database, opts$name)
}

if (opts$build) {
    database <- build(database, pkgs_cache, data_dir, plot_dir)
}

if (opts$archive) {
    database <- archive_tool(database, dir, opts$name)
}

if (opts$restore) {
    database <- restore_archive(database, dir, opts$arc)
}

if (opts$stats) {
   show_stats(database, opts$plot)
}

if (!opts$search && !opts$stats) {
    save_database(database, dir)
}
